### ISSUE TITLE
Why \includepdf and not latex code?

### ISSUE THREAD

**Issue by sylvainschmitt** [cpauvert/latex-template-phd-univ-bordeaux#1]
Hello, thanks for the template and the sharing. I'm just disappointed I discovered it after writing my own template... I was wondering why you made two latex, compiled them into pdf and then included them into your final latex manuscript with \includepdf instead of including the latex page with before_body or something similar directly into your manuscript in latex ?

**Comment by cpauvert** [comment]
Hi Sylvain, 
Thanks for your words. Sorry for the "delay", the template was made in November and I should have reached you sooner.

I chose this _separate_ strategy for two reasons. 
First, adjusting the margins and the layout is much more easier when considering only such special pages. Especially when real names can be longer than expected, or when abstracts need special attention to be nicely formatted. Usually you don't want to make such adjustments to your whole document.
Second, these pages need not to be compiled every time, and though commenting the line could have been done, I preferred to have them done once and for all in PDFs.

Best, 
Charlie
PS: and bonus ^^ you could also send to you color printer the first page and not the entire thesis ;)

**Comment by sylvainschmitt** [comment]
No worry, do not excuse yourself. It's already great that somebody is trying to build a template instead of having everybody trying to follow sometimes blur rules. 

And okay for your strategy. But I think I don't get everything because I'm using my latex templates in combination with Rmarkdown (or the extended version that is Bookdown). But I'm also working with two separate texfiles to finely tune my title and second page. Anyway I keep them as latex and they are also compiled during the compilation of the whole document (and they don't take much time).

But this is not a criticism but more curiosity about your workflow as I'm currently adjusting mine for the thesis writing.
